### ISSUE TITLE
请教个问题： dva-cli 在mac上编译时提示error: spawn eacces；

### ISSUE THREAD

**Issue by 18559909452** [dvajs/dva-cli#104]
fork分支编译出来的；在mac上有如标题错误~ windows正常
用官方的dva-cli貌似没问题。。

**Comment by sorrycc** [comment]
编译指什么？有什么错误？

**Comment by 18559909452** [comment]
@sorrycc 
编译都没错；自己发布的在windows系统下正常； 在mak下win-span报错如题~
后面mac下改权限chmod -R u+x就可以了~      为啥官方的dva-cli不用？

**Comment by sorrycc** [comment]
抱歉，不清楚，可能是你本地的权限问题？
