### ISSUE TITLE
最新版cli工具生成的模板中roadhog版本为0.5.2

### ISSUE THREAD

**Issue by lkspc** [dvajs/dva-cli#108]
用最新版(0.7.9) dva-cli 创建了一个项目，配置了svg发现一直显示不出来，查看了文档说需要roadhog 0.6+。再一看package.json发现roadhog版本为0.5.2

**Comment by NoBey** [comment]
roadhog 版本都是1.1.1 你自己看源代码就知道了

**Comment by lkspc** [comment]
@NoBey 我知道的，git上的模板中是1.1.1，但是npm上的模板里面是0.5.2

**Comment by NoBey** [comment]
我刚看了下确实是0.5.2 应该是上次更新没有发布 我是直接拉下来源码 安装的试试这个方法

**Comment by nolanleung** [comment]
Fixed
