### ISSUE TITLE
npm install dva-cli -g安装失败？

### ISSUE THREAD

**Issue by XuanLuoKryStal** [dvajs/dva-cli#110]
执行npm install dva-cli -g的时候安装失败，是因为node和npm版本的问题吗？错误日志的截取如下：
![image](https://user-images.githubusercontent.com/31084606/29952064-9bf6a27c-8ef9-11e7-8592-2023aad9c16b.png)

**Comment by sorrycc** [comment]
这肯定不是 dva-cli 的问题，检查你的环境配置或者试试 cnpm 。
