### ISSUE TITLE
dva-cli: 0.8.1 new 建出来的项目无法在IE10上跑起来

### ISSUE THREAD

**Issue by duwei54** [dvajs/dva-cli#119]
报语法错误

SCRIPT1002: 语法错误 
index.js, 行3465 字符1
SCRIPT1002: 语法错误 
index.js, 行3465 字符1

看不懂   添加了
import 'babel-polyfill';

也不起作用

**Comment by Cody1988** [comment]
我也遇到同样的问题了，加入pollyfill也不行
