### ISSUE TITLE
创建的app的package.json并没有包含mockjs

### ISSUE THREAD

**Issue by importcjj** [dvajs/dva-cli#12]
使用proxy报错了;

proxy: proxy.config.js parse error

**Comment by sorrycc** [comment]
代码里没用到 mockjs，我试了下 dva-cli 创建新 app，`npm start` 并没有问题。

**Comment by importcjj** [comment]
@sorrycc 那你试试调用mock出来的api，看是不是会报错

**Comment by sorrycc** [comment]
![image](https://cloud.githubusercontent.com/assets/35128/19384217/b30302ce-923a-11e6-9d7e-7a9c7b63048f.png)
没有问题。

**Comment by importcjj** [comment]
嗯， 主要是我参照user-dashboard的例子做下来，在mock代码里引入了mockjs，但是模板app中默认不没有安装。结果调用的时候报了proxy: proxy.config.js parse error，让我困惑了很久，最后才发现是这个原因。
