### ISSUE TITLE
从0.8.1降到0.7.2 新建项目报错

### ISSUE THREAD

**Issue by enlyck** [dvajs/dva-cli#120]
![image](https://user-images.githubusercontent.com/25217307/31008490-e930ab3e-a536-11e7-8c32-24fb95c01d17.png)

另外，我想问下，dva new 出来的项目里，node_modules文件下的项目依赖项的版本号是不是和dva的版本号有关系；

**Comment by sorrycc** [comment]
为啥用 0.7.2 ?

**Comment by enlyck** [comment]
@sorrycc  我想测试不同版本的dva新建出来的项目，node_modules文件下的依赖项版本号是否相同 ,之前随便写的一个版本号，—_—. 换成0.7.4报一样的错

**Comment by sorrycc** [comment]
用最新的吧，老版本没时间测了。
