### ISSUE TITLE
dva-cli 创建的 dva 项目【目录结构问题】

### ISSUE THREAD

**Issue by dkvirus** [dvajs/dva-cli#124]
### 1. feeling

使用 dva-cli 创建 dva 项目，默认会有 models、routes 文件夹，个人感觉在实际开发中存在一些不太方便的感觉。

```
- models
    - rbac
        - security
            + user.js
- routes
    - rbac
        - security
            - user
                + index.js
```

同一个模块（以页面为单位）在开发的时候，会频繁修改 routes 文件和 models 文件，像上面这种目录结构总给人一种翻山越岭的感觉。项目复杂，目录结构层级更多时找起来更是麻烦。

### 2. tips 

改善方式，以模块为单位，同一个模块的文件都写在一个目录下。

```
- rbac
    - security
        - user
            + user.route.js
            + user.model.js
```

**Comment by zjhken** [comment]
确实, 这种文件的存放方式不好, 同一模放同一文件夹更好
