### ISSUE TITLE
为什么初始化的目录一定得是什么都没有的空目录？

### ISSUE THREAD

**Issue by FrendEr** [dvajs/dva-cli#134]
在已有的 git 目录下执行 `dva init` 初始化提示：
![image](https://user-images.githubusercontent.com/11550410/34248719-060db572-e672-11e7-8698-153d7626bb18.png)

目录中仅仅存在 `.git` 目录，这个也不允许初始化

**Comment by dkvirus** [comment]
dva-cli 是将 dva 的脚手架文件复制到当前目录下，你这里可能就只有一个 .git 文件，那其他人如果直接放在c 盘符根目录下，那么创建出来的目录就会和 c 盘下原本的目录搞混淆。dva-cli 这个设置就是为了避免这种情况发生，没毛病，老铁。
