### ISSUE TITLE
请问有没有强缓存配置呢？

### ISSUE THREAD

**Issue by que01** [dvajs/dva-cli#14]
这个手脚架设计时候考虑过这个没有呢？
如果有的话请教一下如何配置呢？

**Comment by sorrycc** [comment]
没明白，详细描述下需求?

**Comment by que01** [comment]
@sorrycc  我的意思是npm run build之后，index.html这个入口里面的js和css是不带文件指纹的，我希望可以有个配置可以带上文件指纹，这样可以避免缓存的问题。
比如默认的index.html里面的css是这样的：
`<script src="common.js"></script>`
but我希望build上线时候是这样的：
`<script type="text/javascript" src="common-1146ec2dc725c94d17c9.js">`

目前我个人查找了一下dva-cli的各种依赖为webpack加上了HtmlWebpackPlugin，然后给build命令加了 --hash参数。

但是还是希望知道设计时候是否已经有这个配置项？

**Comment by sorrycc** [comment]
`atool-build --hash` 会生成带 hash 串的文件，并提供 `map.json`。

**Comment by acmeid** [comment]
@sorrycc `npm run build`  这个构建命令加` --hash`？
还是直接`atool-build --hash` ，这好像是个不存在的命令

**Comment by que01** [comment]
@acmeid 是package.json 里面的 scripts 的 build 命令

**Comment by acmeid** [comment]
@que01 package.json 里面只有下面几个命令
```
"start": "PORT=8085 roadhog server",
"build": "roadhog build",
"lint": "eslint --ext .js src test",
"precommit": "npm run lint"
```

？？

**Comment by que01** [comment]
@acmeid 这样么。。。你这是最新版的 已经从 atool迁徙到roadhog了，看起来你只能等待roadhog项目支持 hash 了，或者你用 webpack.config.js 做配置自己硬上(我暂时没试过，老版本没升级就是因为 hash 问题，我也不知道现在支持没有)。。。。

**Comment by acmeid** [comment]
@que01 嗯嗯，我看了roadhog也没有相关的配置。dva没有webpack.config.js这个文件。除非不用dva了，自己去配置
