### ISSUE TITLE
 dva generate is disabled since we don't have enough time currently

### ISSUE THREAD

**Issue by lizhancheng** [dvajs/dva-cli#140]
**dva version: 0.9.2**
**platform: window 7**
> run command: **dva g route users**
`error info: dva generate is disabled since we don't have enough time currently.`

**Comment by sorrycc** [comment]
这是对的，dva generate 不支持了，时间不够。

**Comment by lizhancheng** [comment]
是已经不能用dva g这个是吧？是不是要更新一下README？

**Comment by AndroidIosWebEmbeddedFirmwareDver** [comment]
啥意思？？？
