### ISSUE TITLE
dva-cli升级到v0.9.2后没有.roadhogrc文件,那么现在我该怎么引用antd的样式?

### ISSUE THREAD

**Issue by Glassay** [dvajs/dva-cli#141]
我看官方项目实战里现在好像是编辑 .webpackrc，使 babel-plugin-import 插件生效。我像下面这样写的：
`{
"extraBabelPlugins": [
  ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": "css" }]
],
}`
但是启动之后terminal报错如下：
Unexpected token } in JSON at position 110

**Comment by sorrycc** [comment]
检查 JSON 错误。

**Comment by sorrycc** [comment]
逗号之类的。
