### ISSUE TITLE
`dva g component ProductList` shows `dva generate is disabled since we don't have enough time currently.`

### ISSUE THREAD

**Issue by BrickXu** [dvajs/dva-cli#142]
as subject, and here is my env detail:

```
dva-cli version 0.9.2
    dva version 2.1.0
roadhog version 2.0.6
```

**Comment by sorrycc** [comment]
> dva generate is disabled since we don't have enough time currently.

由于目前我们没有足够的时间，dva生成被禁用。

**Comment by ThaddeusJiang** [comment]
@sorrycc 有没有推荐的 dva 替代品？

**Comment by tawen** [comment]
是版本问题吗，用老板是否可以，我也遇到同样的问题？

**Comment by BrickXu** [comment]
直接删了那段信息以及process.exit(0)，依然可以继续使用。

**Comment by nanxiaobei** [comment]
「由于目前我们没有足够的时间，dva生成被禁用。」

这句话是啥意思？谁没有时间？dva 团队没时间，还是 dva 没时间？「禁用」是什么意思？可以开启吗？还是以后都没有这个功能了？

**Comment by wsYdd** [comment]
能看得懂英文，问题是怎么解决啊？？？
