### ISSUE TITLE
新版本dva new后怎么没了.roadhogrc

### ISSUE THREAD

**Issue by firemoon2000** [dvajs/dva-cli#146]
原来的dva-cli生成的专案还有一个.roadhogrc 文件用来写roadhog里的各种配置.
但是最新的dva-cli生成专案这个文件没了.而是多了一个.webpackrc
这是要改回webpack了吗?

我应该怎么处理
A.新增一个.roadhogrc,删除.webpackrc 并且沿用以前方法
B.放弃roadhog学习webpack?
望告知

**Comment by sorrycc** [comment]
roadhog 升级 2 之后使用 .webpackrc 进行配置，参考 https://github.com/sorrycc/roadhog/blob/master/migrate-from-1.x_zh-cn.md 。
