### ISSUE TITLE
希望能增加一个更新日志0.7版都有.roadhogrc 而0.9版就没有该文件了？为什么

### ISSUE THREAD

**Issue by walkinMrwang** [dvajs/dva-cli#147]

**Comment by sbl1996** [comment]
参见[roadhog 2.0 发布](https://github.com/sorrycc/blog/issues/55,)
> 同时，为了更通用，配置文件从 .roadhogrc 更名为 .webpackrc

**Comment by sorrycc** [comment]
CHANGELOG 在这里，https://github.com/sorrycc/roadhog/releases
