### ISSUE TITLE
使用最新的cli创建项目，ie10出错

### ISSUE THREAD

**Issue by myGitZone** [dvajs/dva-cli#153]
The \<AuthorizedRoute \/> component appears to have a render method, but doesn't extend React.Component. This is likely to cause errors. Change AuthorizedRoute to extend React.Component instead.

感觉是安装babel插件升级问题，但是能力有限，谢谢

**Comment by sorrycc** [comment]
哪里有 `AuthorizedRoute` ?

**Comment by myGitZone** [comment]
您好，这个是用的Ant Design Pro的路由权限控制，我只是写了一个demo。早上我试了下，将dva-cli初始化的项目IndexPage改成继承PureComponent。在ie10也会报上面的错。是不是近期babel插件升级导致。谢谢

**Comment by myGitZone** [comment]
补充：然后我同样使用create-react-app创建的项目，安装dva。使用相同的代码进行测试，没有类似的问题。麻烦您了
