### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by theSouthSea** [dvajs/dva-cli#157]
dva-cli version 1.0.0-bea.2创建新项目后npm start启动，打开的是index.js报Uncaught SyntaxError: Unexpected token <。
package.json配置
{
  "private": true,
  "scripts": {
    "start": "umi dev",
    "build": "umi build",
    "lint": "eslint --ext .js src test",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "dva": "^2.2.3",
    "umi": "^1.0.0-0",
    "umi-plugin-dva": "^0.1.6"
  },
  "devDependencies": {
    "dva-loading": "^2.0.1",
    "eslint": "^4.14.0",
    "eslint-config-umi": "^0.1.1",
    "eslint-plugin-flowtype": "^2.34.1",
    "eslint-plugin-import": "^2.6.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0",
    "globby": "^8.0.1",
    "husky": "^0.12.0"
  }
}

**Comment by sorrycc** [comment]
Try dva-cli@1.0.0-beta.4 .
