### ISSUE TITLE
version 0.10.0 启动报错 ./node_modules/history/esm/history.js

### ISSUE THREAD

**Issue by guyongliang** [dvajs/dva-cli#169]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
- 1.dva new app0
- 2.npm start

#### Expected behavior: (预期的正常效果)
正常进入启动页

#### Actual behavior: (实际效果)
报错：
./node_modules/history/esm/history.js
Module not found: Can't resolve '@babel/runtime/helpers/esm/extends' in 
'“项目路径所在绝对路径”\node_modules\history\esm'

#### Versions of packages used: (哪个库的哪个版本出现的问题)
dva-cli version  0.10.0

将版本回退到1.0.0-beta.4 可以正常启动

**Comment by ZY2071** [comment]
回退到 1.0.0-beta.4 ?
