### ISSUE TITLE
修改 mock 目录文件 proxy 并不会 reload

### ISSUE THREAD

**Issue by Alex1990** [dvajs/dva-cli#18]
每次都要重新`npm start`

**Comment by sorrycc** [comment]
这里有配 watchDirs 吗? https://github.com/dvajs/dva-cli/blob/3c4e8a8/boilerplates/app/package.json#L26

**Comment by Alex1990** [comment]
👍 从我初始化之后， dva-cli 更新了不少东西啊，我还看了 CHANGELOG 的，没发现这里已经改了
