### ISSUE TITLE
对extract-text-webpack-plugin模块的支持不是很好

### ISSUE THREAD

**Issue by liushaohua** [dvajs/dva-cli#20]
ERROR in ./src/index.css
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/Users/liushaohua/Documents/DATA/UI/myApp/node_modules/.1.0.1@extract-text-webpack-plugin/loader.js:21:9)
 @ ./src/index.js 5:0-22

**Comment by sorrycc** [comment]
node 版本?

**Comment by liushaohua** [comment]
node 6.1.0存在问题，更换6.4.0后fix
