### ISSUE TITLE
request.js返回状态为0

### ISSUE THREAD

**Issue by wm3445** [dvajs/dva-cli#26]
跨域访问，浏览器返回的状态
Request URL:http://192.168.31.144:8080/test/api/login?
Request Method:GET
Status Code:200 OK
Remote Address:192.168.31.144:8080
但是封装的request.js status返回0
 Object {err: Error at checkStatus (webpack:///./src/utils/request.js?:24:15)}

**Comment by sorrycc** [comment]
这是跨域 xhr 请求的问题吧，google 下吧。https://www.google.com/search?%7Bgoogle:acceptedSuggestion%7Doq=cross+domain+xhr&%7Bgoogle:instantFieldTrialGroupParameter%7Dsourceid=chrome&ie=UTF-8&q=cross+domain+xhr

**Comment by wm3445** [comment]
`
export async function changeCheckCode(params) {
  return request(`http://192.168.0.107:8080/test/api/captcha`, {
    method: "get",
    mode: "no-cors",
    credentials: 'include',
  });
}
`
使用的是fetch 
![c68c999e-802f-4a3b-bd7d-341df0145cc3](https://cloud.githubusercontent.com/assets/5467635/20779534/0f665512-b7b0-11e6-8af3-4e7e75b54e91.png)
返回错误
![ff5ecd05-d98e-4150-8059-140be69bd3ad](https://cloud.githubusercontent.com/assets/5467635/20779635/adab908e-b7b0-11e6-826f-231a1104e850.png)

浏览器返回
![567fcdf6-aa28-4888-9246-a71cefc241b7](https://cloud.githubusercontent.com/assets/5467635/20779652/bf4ead9e-b7b0-11e6-970e-549a779d7ee3.png)

**Comment by sorrycc** [comment]
服务端要支持的，返回允许跨域请求的头信息。

**Comment by extensivewang** [comment]
@wm3445 问题解决了吗？

**Comment by extensivewang** [comment]
![aaaa](https://cloud.githubusercontent.com/assets/3365260/21003706/d7feec92-bcfa-11e6-9e1a-7fcd1f694db1.png)
why?

**Comment by extensivewang** [comment]
const ops = {
    method: 'POST',
    mode: 'no-cors',
    credentials: 'include',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      Authorization: 'Bearer ' | cookie.get('access_token'),
    },
  };

**Comment by sorrycc** [comment]
这是跨域问题，请自行 google 解决。https://www.google.com/search?%7Bgoogle:acceptedSuggestion%7Doq=request+status+0&%7Bgoogle:instantFieldTrialGroupParameter%7Dsourceid=chrome&ie=UTF-8&q=request+status+0

**Comment by hst-Sunday** [comment]
@wm3445@rujianwang
请问是如何解决的呢？
