### ISSUE TITLE
使用dva g compontent命令无法生成相应代码

### ISSUE THREAD

**Issue by l745230** [dvajs/dva-cli#28]
请问是什么地方没配置好吗?
![8e300029-e0ca-48ae-b5e2-f6a0f9e2ca7d](https://cloud.githubusercontent.com/assets/15940920/20910340/e3a6d376-bb9b-11e6-9dd7-68d3d73d8681.png)

**Comment by sorrycc** [comment]
node 版本用 6.7 试试。

**Comment by l745230** [comment]
谢谢,切换到6.7版本可以生成了

**Comment by sorrycc** [comment]
ok，下个版本我加个提示。
