### ISSUE TITLE
脚手架支持 typescript

### ISSUE THREAD

**Issue by nikogu** [dvajs/dva-cli#3]
打算先搞一个 `typescript` 的模板放在 boilerplates 下面，稍后提个 pr

**Comment by sorrycc** [comment]
你可以先试试看，但维护多个脚手架会很麻烦，后面的智能研发工具以及 addon 机制都会依赖语法分析 (dva-ast)，多个脚手架意味着维护多套语法规则。typescript 如果足够好用，后期可以考虑通过 addon 的机制加入，但不是提供多套脚手架。

**Comment by nikogu** [comment]
前几天研究了一下，发现 atool-build 已经支持 typescript，基本上不需要如何改动就可以改写成 typescript，如果后面有需求感觉出一份指南就可以搞定了，关注后续 addon
