### ISSUE TITLE
npm build 命令完成后没有出现 dist目录

### ISSUE THREAD

**Issue by linyongping** [dvajs/dva-cli#30]
`node -v  7.2.0`
`npm -v  3.10.9`
`dva -v  0.6.0` 

`npm start `开发时一切正常，
但是使用`npm build`打包时命令看起来像是成功了，没有任何报错信息，但是却没有输出任何目录或文件

截图在此
![capture](https://cloud.githubusercontent.com/assets/13087561/20957160/0d29fac8-bc89-11e6-80ad-44f0232c387c.PNG)

**Comment by sorrycc** [comment]
npm run build

**Comment by linyongping** [comment]
问题解决，感谢
