### ISSUE TITLE
Improve dva-cli console infomation

### ISSUE THREAD

**Issue by afc163** [dvajs/dva-cli#31]
```
╔═════════════════════════════════════════════════════════╗
║  Flaming Cloud Project started : http://127.0.0.1:8000  ║
╚═════════════════════════════════════════════════════════╝
```

Make local development url clear and beautiful.

**Comment by sorrycc** [comment]
![](https://camo.githubusercontent.com/8eca8ee125915f695865cb3fb96eaf3dbfd9f707/68747470733a2f2f7a6f732e616c697061796f626a656374732e636f6d2f726d73706f7274616c2f76706b774f74584e756b58706551424e546f45622e676966)
