### ISSUE TITLE
supply better way to customize webpack config

### ISSUE THREAD

**Issue by afc163** [dvajs/dva-cli#33]
https://github.com/dvajs/dva-cli/blob/master/boilerplates/demo/webpack.config.js#L15-L34

These code is complex and hard to modify.

**Comment by sorrycc** [comment]
https://github.com/sorrycc/roadhog#配置
已采用 JSON 的配置方式，比如 app 脚手架的配置是这样，https://github.com/dvajs/dva-cli/blob/5961c6e/boilerplates/app/.roadhogrc
