### ISSUE TITLE
'dora' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by Jogen** [dvajs/dva-cli#36]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "d:\\ProgramFiles\\NodeJs\\node.exe" "d:\\ProgramFiles\\NodeJs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! @ start: `dora --plugins "proxy?watchDirs=./mock,webpack,webpack-hmr"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'dora --plugins "proxy?watchDirs=./mock,webpack,webpack-hmr"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     dora --plugins "proxy?watchDirs=./mock,webpack,webpack-hmr"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     e:\ANTD\dva-quickstart\npm-debug.log

npm start启动时报错

**Comment by sorrycc** [comment]
感觉应该是依赖没装好，删除 node_modules 重装试试。

**Comment by Jogen** [comment]
确实是依赖没装好，新手第一次用，谢谢
