### ISSUE TITLE
关于 sousemap 被破坏的问题

### ISSUE THREAD

**Issue by zsl99a** [dvajs/dva-cli#38]
据我个人研究得出结论   webpack 和babel 的sousemap 是不能叠加使用的 ，这就导致同时使用多个 loader 对一个文件做处理的时候 sousemap 会被破坏，
所以我认为： 正确的做法是 把 webpack 单纯作为打包工具 ，而将 编码转换的工作全部放在 babel 中  比如 es3ify-loader  用   es3ify-webpack-plugin替代    
是对官方的建议， 也望部分使用sousemap进行调试的同学少走弯路

**Comment by sorrycc** [comment]
👏🏼 感谢建议！结果是对的，但原因不对，不是 sourcemap 不能叠加，而是 es3ify-webpack-plugin 处理了 sourcemap，但 es3ify-loader 没有。
