### ISSUE TITLE
dva new dva-quickstart报错，dva npm也报错，请问知道是什么问题吗

### ISSUE THREAD

**Issue by OliveKong** [dvajs/dva-cli#39]
![image](https://cloud.githubusercontent.com/assets/7875818/21303085/d4a2663c-c5f6-11e6-9fba-a545790333a5.png)
请问知道这是什么意思吗？
下图是npm start运行后的错误提示
![image](https://cloud.githubusercontent.com/assets/7875818/21303116/05ec1e90-c5f7-11e6-8ce3-23b0f59f74b1.png)

**Comment by sorrycc** [comment]
依赖没有装好，删除 node_modules 重装试试。
