### ISSUE TITLE
跟着你快速上手的小项目，出现错误，看不出来哪里有问题，可以给些指示吗？

### ISSUE THREAD

**Issue by OliveKong** [dvajs/dva-cli#40]
![image](https://cloud.githubusercontent.com/assets/7875818/21304321/5acc40ae-c5ff-11e6-8536-da878f4ed0f4.png)

**Comment by sorrycc** [comment]
这个先忽略吧，windows 下装 openssl 比较麻烦。

**Comment by sorrycc** [comment]
可以根据这个教程来，已无 openssl 的问题。https://www.github.com/sorrycc/blog/issues/18
