### ISSUE TITLE
使用hashHistory，init后不会触发hashchange

### ISSUE THREAD

**Issue by hellheaven** [dvajs/dva-cli#42]
用的代码如下
import { useRouterHistory} from 'dva/router';
import { createHashHistory} from 'history';
const app = dva({
  history: useRouterHistory(createHashHistory)({ queryKey: false }),
});

使用hashHistory，init后不会出发hashchange，导致页面打开空白。
必须手动在地址栏触发一下hash change.

**Comment by sorrycc** [comment]
```
useRouterHistory(createHashHistory)({ queryKey: false }),
```

别关掉这个。

**Comment by hellheaven** [comment]
queryKey:true ?
true也不行，而且我的本意就是去掉_k查询参数。

**Comment by sorrycc** [comment]
别去掉，去掉会有奇怪问题。

**Comment by hellheaven** [comment]
好吧。有空再看下原因。
