### ISSUE TITLE
更新为roadhog后,项目异常卡顿

### ISSUE THREAD

**Issue by sunui** [dvajs/dva-cli#48]
主要是浏览器打开项目页面后消耗大量的cpu和内存,打开浏览器后基本没法编码,因为编辑器打字已经很卡了.而且其他大型项目都没出现过这种情况.我的电脑配置还可以的.
不知各位有没有这种情况?  性能问题源头在哪? roadhog吗?

**Comment by sorrycc** [comment]
还没遇到过类似反馈，重启电脑试试。。

**Comment by sunui** [comment]
@sorrycc  嗯又做了一些排查, 发现不是浏览器的原因,打字的时候是atom霸占的cpu疯狂上涨,   但没弄明白具体原因,因为别的项目没有这种情况,会不会是项目有监听编辑器的相关默认配置呢?
