### ISSUE TITLE
项目没开发完，dva-cli改得dora都不用了？

### ISSUE THREAD

**Issue by longzb** [dvajs/dva-cli#52]
用dva项目开发到一小半，今天无聊用dva-cli创建个项目看看变了没，这一看吓一跳啊！webpack.config.js都不得了，试问？我是继续用之前的开发还是重新用dva-cli创建，然后把代码一个一个的复制过去？把之前的less全部改成你们默认的css??或者有其他更好的办法？？

**Comment by sorrycc** [comment]
之前的用着没问题就不用改，想更好的工具体验，可以参考 https://github.com/sorrycc/blog/issues/17 切换到 roadhog，就几个步骤。
