### ISSUE TITLE
请问有没有打算把文件md5戳的功能集成进来？

### ISSUE THREAD

**Issue by whwnow** [dvajs/dva-cli#57]
类似webpack的chunkhash的功能，感觉这个功能还是挺常用的，方便做静态缓存。

**Comment by sorrycc** [comment]
关注 https://github.com/sorrycc/roadhog/issues/69 ，下个版本加。

**Comment by yujiayinshi** [comment]
@sorrycc 请问这个特性现在有了吗？

**Comment by sorrycc** [comment]
@yujiayinshi 关注 roadhog 发布，这周会加上。
