### ISSUE TITLE
安装最新版的dva-cli 无法运行提示错误

### ISSUE THREAD

**Issue by huanglei1991** [dvajs/dva-cli#59]
![image](https://cloud.githubusercontent.com/assets/25176774/22023865/ee768930-dd02-11e6-8e5e-63e718403140.png)

- 环境node v6.9.4 LTS win10系统
没改过任何代码

**Comment by sorrycc** [comment]
最新版在 win 下好像有问题，先用 dva-cli@0.7 吧。Ref：https://github.com/sorrycc/roadhog/issues/88

**Comment by devin-yuan** [comment]
mac 下同样有问题
testdva dva -v
0.7.8
testdva node -v
v6.9.4
npm -v
3.10.10

**Comment by sorrycc** [comment]
试试把 npm 升级到最新，https://github.com/sorrycc/roadhog/issues/99#issuecomment-273964812
