### ISSUE TITLE
执行npm start的时候报错

### ISSUE THREAD

**Issue by niyg** [dvajs/dva-cli#63]
![image](https://cloud.githubusercontent.com/assets/14817820/22816815/10712b18-ef9f-11e6-89c6-6814c5ea1781.png)
新手刚使用，这是什么原因呢

**Comment by sorrycc** [comment]
依赖没装全? 删除 node_modules 重装试试。

**Comment by niyg** [comment]
@sorrycc 嗯嗯，可以了谢谢
