### ISSUE TITLE
dva g route users 报错

### ISSUE THREAD

**Issue by oo6890049** [dvajs/dva-cli#64]
![11111](https://cloud.githubusercontent.com/assets/8954811/22863058/d88ecb60-f174-11e6-91b4-622d6ac485e6.jpg)
![222222](https://cloud.githubusercontent.com/assets/8954811/22863064/e77bb534-f174-11e6-91ce-ff1e245e6225.jpg)
node v6.9.5
npm v4.2.0
cnpm v4.3.0
删除node_modules 重新npm install 依然如此

**Comment by oo6890049** [comment]
删除node_modules 重新npm install 依然如此

**Comment by sorrycc** [comment]
看报错就是 npm 依赖的问题，删除 node_modules 用 [cnpm](https://github.com/cnpm/cnpm) 安装试试？

**Comment by oo6890049** [comment]
@sorrycc 我感觉也是npm依赖的问题。但是无论是使用npm还是cnpm，重新安装node、npm依然是此报错信息，不知如何解决了

**Comment by sorrycc** [comment]
手动安装缺失依赖，`cnpm i babel-runtime -g` 试试呢?

**Comment by oo6890049** [comment]
@sorrycc 谢谢  cnpm i babel-runtime -g 解决此问题
