### ISSUE TITLE
dva g model 生成文件的缓存问题

### ISSUE THREAD

**Issue by adam1985** [dvajs/dva-cli#69]
使用dva g model 生成文件，后来对model文件重命名，服务重启之后报错，提示之前文件module没找到，能通过什么方式删除缓存吗？

Failed to compile.

Error in ./src/index.js
Module not found: ./models/users

@ ./src/index.js 24:10-35 66:42-67 67:4-74:6 70:18-43 92:44-69 93:4-100:6 96:18-43 118:44-69 119:4-126:6 122:18-43

**Comment by sorrycc** [comment]
`./src/index.js` 里没有改引用吧?

**Comment by ameol** [comment]
把在index的引用换个行保存就好了...
不过还有其他一些缓存问题，比如我用antd-mobile组件，属性写错了，提示报错，我删了还是有错误消息

**Comment by EdenLiang** [comment]
貌似，node_modules\.cache，里面删除babel-loader，然后重新启动，就好了
