### ISSUE TITLE
打包出来的体积为什么这么大

### ISSUE THREAD

**Issue by tianez** [dvajs/dva-cli#71]
打包出来的代码比它显示出来的大小 大了很多很多

如图：
![2200](https://cloud.githubusercontent.com/assets/6291579/23541911/3b3505f4-0025-11e7-821d-4b3982d63cd2.jpg)
![2213](https://cloud.githubusercontent.com/assets/6291579/23541915/43020ff2-0025-11e7-8bfb-b6b61d93c48b.jpg)

**Comment by tianez** [comment]
![image](https://cloud.githubusercontent.com/assets/6291579/23541943/653ada5e-0025-11e7-8394-ed2b1a18552e.png)
.roadhogrc 配置

**Comment by sorrycc** [comment]
这个尺寸正常的吧

**Comment by tianez** [comment]
![image](https://cloud.githubusercontent.com/assets/6291579/23594159/a02844ce-0252-11e7-8a92-bab30d2d2e59.png)
这个是用demo 中的 antd-admin 的打包方式打包出来的
后来迁移用 roadhog的方式进行打包
程序代码未变   打包后体积大了1M多

**Comment by tianez** [comment]
哦 ，还是小有改动
改动后体积应该是要变小的

**Comment by wuyunjiang** [comment]
什么原因，我也是实际文件大小，比控制台输出的大许多

**Comment by sorrycc** [comment]
显示的是 gzip 之后的尺寸。。
