### ISSUE TITLE
dva-cli现在创建新的项目后，没有webpack-config.js了吗？

### ISSUE THREAD

**Issue by chaplin8** [dvajs/dva-cli#72]
dva-cli现在创建新的项目后，没有webpack-config.js了吗？我记得之前用dva创建的项目里面是有webpack.config.js的，昨天重新创建了一个，发现跟之前变的好多了。还有，假如我想在项目里面引用assets里面的图片的话，路径该怎么获得？

**Comment by xiandongw** [comment]
It uses .roadhogrc now. You can reference the images from assets directly like:
 <link rel="icon" href="./assets/xxx-logo.png" type="image/x-icon">

**Comment by sorrycc** [comment]
可以放 `public` 目录，https://github.com/sorrycc/roadhog#使用-public-目录 。
