### ISSUE TITLE
"npm test" fails with "系统找不到指定的路径。"

### ISSUE THREAD

**Issue by xiandongw** [dvajs/dva-cli#73]
There is error when run "npm test".

reproduce steps:
1. add {"test": "roadhog test ./src/**/specs/*.js"} in package.json
2. run npm test

It works if run "roadhog test ./src/**/specs/*.js" in terminal.

I compared the node_modules/roadhog under project and system npm directory(global roadhog cmd location). The node_modules is missing for roadhog under project. I can reproduce this with any new project created through dva-cli.

Can this be fixed easily?

It seems [beta1 ](https://github.com/sorrycc/roadhog/pull/147)of roadhog fixed this. But not succeed to download the fix.

**Comment by sorrycc** [comment]
+ roadhog@0.6.0-beta2
