### ISSUE TITLE
使用dva创建的ant design项目启动不了

### ISSUE THREAD

**Issue by fzypzl** [dvajs/dva-cli#8]
用dva new project后，进入project目录，npm start
控制台输出
err with request:Error:socket hang up /
err with request Error:socket hang up /favicon.ico
http://localhost:8989/打开是个空白页面，chrome的控制台也没有输出js错误
新建项目是ok的，我修改了js的内容，就这样了，然后我撤销到最初状态也是不行
昨天晚上我新建的项目，启动不了就去休息了，今天早上我开始工作的时候试了一下，
神奇般的可以启动了，我修改后又不行了，撤销修改的内容也不行
真让人崩溃
用这个用的心惊胆战的，不知道它什么时候就启动不了了

**Comment by sorrycc** [comment]
访问 http://localhost:8000/ 呢?

**Comment by fzypzl** [comment]
@sorrycc ,8000可以，我看到控制台中输出的是在监听8989端口，谢谢你

**Comment by sorrycc** [comment]
package.json 中搜下 proxy，把他去掉，就提示 8000 端口了。

**Comment by hqwlkj** [comment]
如何修改端口号呢？ @sorrycc
