### ISSUE TITLE
What are `mock` dir and `.roadhogrc.mock.js` for?

### ISSUE THREAD

**Issue by oluckyman** [dvajs/dva-cli#84]
After running `dva new myApp` I have empty `mock/` dir and `.roadhogrc.mock.js` file.
When do I need them? Can I delete them? Was not able to find the answers in issues and docs...

**Comment by iamzhouyi** [comment]
This repo sample may answer ur question, I think.
https://github.com/zuiidea/antd-admin

**Comment by oluckyman** [comment]
wow, thanks!
