### ISSUE TITLE
用dva new app生成项目，出现err with request :Error: socket hang up 

### ISSUE THREAD

**Issue by jove983413** [dvajs/dva-cli#9]
你好！
 dva new app
 cd app
 npm start

后访问出现如下的错误，请问要如何解决？
E:\app>npm start

> @ start E:\app
> dora --plugins "proxy,webpack,webpack-hmr"

          proxy: load rule from proxy.config.js
          proxy: listened on 8989
�  459/459 build modules
webpack: bundle build is now finished.
err with request :Error: socket hang up  /
err with request :Error: socket hang up  /favicon.ico

我看了问题 #8 和我的好像是一样的，但是我用http://localhost:8000不能访问，去掉proxy也不行，奇怪了

---- 把端口改为8001可以了"start": "dora -p 8001 --plugins \"webpack,webpack-hmr\""

但是如何使用proxy呢？

**Comment by sorrycc** [comment]
proxy 在 windows 下有各种奇怪的问题，先不要用了吧。

**Comment by caolinbo** [comment]
npm start

'openssl' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'openssl' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
=============
rootCA generated at :
C:\Users\16619\.anyproxy_certs
=============
rootCA generated
please trust the rootCA.crt in C:\Users\16619\.anyproxy_certs\
or you may get it via anyproxy webinterface

如何处理？
