### ISSUE TITLE
root.findRouters(...).getRouterInfo is not a function

### ISSUE THREAD

**Issue by gongchao** [dvajs/dva-cli#91]
```base
$ dva g route product-list
/Users/gongchao/.nvm/versions/node/v7.4.0/lib/node_modules/dva-cli/bin/dva-generate
      create  routeComponent src/routes/ProductList.js, src/routes/ProductList.css
TypeError: root.findRouters(...).getRouterInfo is not a function
    at transform (/Users/gongchao/.nvm/versions/node/v7.4.0/lib/node_modules/dva-cli/node_modules/dva-ast/lib/transform.js:42:32)
    at exports.default (/Users/gongchao/.nvm/versions/node/v7.4.0/lib/node_modules/dva-cli/node_modules/dva-ast/lib/api/index.js:46:36)
    at /Users/gongchao/.nvm/versions/node/v7.4.0/lib/node_modules/dva-cli/lib/generate.js:92:27
    at generate (/Users/gongchao/.nvm/versions/node/v7.4.0/lib/node_modules/dva-cli/lib/generate.js:108:11)
    at Object.<anonymous> (/Users/gongchao/.nvm/versions/node/v7.4.0/lib/node_modules/dva-cli/bin/dva-generate:11:27)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by sp121933039** [comment]
我也是这个疑难杂症！

**Comment by jzoe** [comment]
+1

**Comment by serical** [comment]
+1

**Comment by heianqishizhisuiyuan** [comment]
我也是这个错误 求解决

**Comment by wupinlang** [comment]
+1 求解决

**Comment by zjcwill** [comment]
+1

**Comment by GreenAppleOne** [comment]
我也这个问题，怎么折腾都不行

**Comment by miaozilong** [comment]
我回退版本到0.7.0和0.7.6   也报错  但是错误还不一样  晕死。。。

**Comment by qiutiaoming** [comment]
+1

**Comment by wenris** [comment]
这个 bug 让我怀疑自己人生。问题的根源是，我们使用的 **dva-cli** > **dva-ast** > **jscodeshift** 的版本不对！

**dva-ast** 中使用了下面的代码：

```js
Collection.fromPaths([], this);
```

`Collection` 是 **jscodeshift** 库提供的，**dva-ast** 的 `package.json` 指定 `"jscodeshift": "^0.3.28"` ，但 **jscodeshift** 最新版本是 `0.3.32` ，这里 Bug 就出现了。

虽然我发现了问题根源，但 **dva-ast** 和 **jscodeshift** 这两个库的源代码看得我云里雾里，望而生畏，杀虫的工作还是等高手吧。

我目前的解决方法是，将全局安装的 **jscodeshift** 回滚至 `0.3.28` ，初入江湖的我，人生还可以继续么？

Roll your global package **jscodeshift** back to `v0.3.28`  .

**Comment by wenris** [comment]
已经在 **dva-ast** 打了臭虫报告，应该很快可以修复的。

https://github.com/dvajs/dva-ast/issues/39

**Comment by heianqishizhisuiyuan** [comment]
不对呀 你在哪修改jscodeshift呀  怎么找到的呀

**Comment by wenris** [comment]
@heianqishizhisuiyuan 

在全局包目录中，当安装 **dva-cli** 时依赖而来的。不同方式，如 `npm` 、 `yarn` 、 `nvm` 安装的目录的都不一样，你可以从报错中推出的，如：
```
$ dva g route product-list
/Users/gongchao/.nvm/versions/node/v7.4.0/lib/node_modules/dva-cli/bin/dva-generate
      create  routeComponent src/routes/ProductList.js, src/routes/ProductList.css
...
```
则 **jscodeshift** 应该在 `/Users/gongchao/.nvm/versions/node/v7.4.0/lib/node_modules/jscodeshift` 目录下。

**Comment by heianqishizhisuiyuan** [comment]
@gongchao   谢谢大神 找到了  而且  确实把jscodeshift 改成0.3.28 版本后能用了  哈哈

**Comment by lingfulu** [comment]
![default](https://user-images.githubusercontent.com/23699899/27817501-fea0fec2-60c3-11e7-89ad-31c19db1d6ee.PNG)
把jscodeshift 改成0.3.28 版本这个问题解决了,但是有出空心啊一个报错
![2](https://user-images.githubusercontent.com/23699899/27817558-654936da-60c4-11e7-8978-28e0cf66dd32.PNG);
大神们求解!

**Comment by wenris** [comment]
很明显的错误是由于文件已存在，删除 `src/routes/Users.js` 和 `src/routes/Users.css` 再试。

**Comment by EthanOrange** [comment]
@wenris  bug反馈这么多天了 还没修复啊

**Comment by liujun9562** [comment]
@lingfulu 请问你那个问题解决了吗？跟你报一样的错


#

**Comment by Raoul1996** [comment]
@wenris 谢谢，更改文件之后已经可以使用了

**Comment by GreenAppleOne** [comment]
真是奇怪了 ，bug为啥不修复 ，快速出个版本不就行了吗？感觉整个dva 所有项目都是拖拖拉拉的，roadhog也是这个样子，是不是没有精力搞了呢

**Comment by chenkan** [comment]
代码已经修复了, 但是 npm 包还没有更新吧@sorrycc @ChrisFan 
see: https://github.com/dvajs/dva-ast/pull/41/files

**Comment by sorrycc** [comment]
dva-cli@0.7.9，已修复。

**Comment by hudarui** [comment]
辛苦了，大神
